# Generated by Django 4.0.3 on 2022-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='wilaya',
            new_name='job',
        ),
        migrations.AddField(
            model_name='members',
            name='DateDiag',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='Dbirthday',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='MdeFam',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='NumMdeFam',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='Pbirthday',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='Sfin',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='Ssante',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='adresse',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='cancerType',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='etatCivil',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='medcinNote',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='number',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='poids',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
