# Generated by Django 4.0.3 on 2022-04-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basstore', '0002_rename_wilaya_members_job_members_datediag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='medcinNote',
            field=models.CharField(default='null', max_length=9000),
        ),
    ]
